use_frameworks!

platform :ios, '9.0'

target 'ORCoreData_Example' do
  pod 'ORCoreData', :path => '../'

  target 'ORCoreData_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
