source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ORCoreData_Example' do
  pod 'ORCoreData', :path => '../'
end

target 'ORCoreData_Tests' do
  pod 'ORCoreData', :path => '../'

  
end
